### ISSUE TITLE
command/pr, command/list: Fails if a file is deleted when building list of tests

### ISSUE THREAD

**Issue by gdavison** [katbyte/tctest#50] opened 2020-11-27 19:28 UTC
When running the `tctest pr <pr number>` or `tctest list <pr numberr>` commands on a PR which deletes a file, it fails with the following error

```console
$ tctest pr 16467
Discovering tests for pr #16467 (https://github.com/terraform-providers/terraform-provider-aws/pull/16467)...
ERRO[2020-11-27 11:19:24] tctest: pr cmd failed: pr list failed: downloading file (aws/internal/tfawsresource/testing_test.go) metadata: GET https://api.github.com/repositories/93444615/contents/aws/internal/tfawsresource/testing_test.go?ref=e9457fd5f715fc381621b558e33018cf7cec0119: 404 Not Found [] 
```

If the user provides a test regex, it does not fail

```console
tctest pr 16467 TestAccDataSourceAwsRoute53ResolverRules_basic
triggering refs/pull/16467/merge for TestAccDataSourceAwsRoute53ResolverRules_basic...
  build 12345 queued: https://teamcity.example.com/viewQueued.html?itemId= 12345
```

**Comment by katbyte** [comment] 2021-01-03 17:43
This might be fixed on master now @gdavison

**Comment by katbyte** [comment] 2021-01-03 17:49
duplicate of #17 ?

**Comment by katbyte** [comment] 2022-08-04 01:14
closing as duplicate of https://github.com/katbyte/tctest/issues/17

**Closed by katbyte** 2022-08-04 01:14 UTC
